name: aura_control
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  connectivity_plus: ^6.1.4
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  dartssh2: ^2.12.0
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.10
  go_router: ^15.1.2
  path_provider: ^2.1.5
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.10.0
  intl: any
  file_picker: ^10.1.7
  android_intent_plus: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
    - assets/AuraYSeneca.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash2.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
  web_image_mode: scale
  fullscreen: true
  android_12:
    color: "#ffffff"
    image: assets/splash2.png
